name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - documentation/*
    - LICENSE
    - README.md
    - CHANGELOG.md
    - TESTING.md
    - CONTRIBUTING.md
    - .mailmap
    - .rubocop.yml
    - .gitignore
    - chefignore

pr:
  branches:
    include:
    - master
    - release/*
  paths:
    exclude:
    - documentation/*
    - LICENSE
    - README.md
    - CHANGELOG.md
    - TESTING.md
    - CONTRIBUTING.md
    - .mailmap
    - .rubocop.yml
    - .gitignore
    - chefignore

resources:
  repositories:
  - repository: templates
    type: git
    name: chef-pipelines-templates

parameters:
  - name: kitchenSuites
    displayName: Kitchen Suites
    type: object
    default:
      - default
      - software-updates
      - spotlight
      # - xcode-from-apple
      # - xcode-from-url
      - command-line-tools
      - certificate
      - users
      - keychain
      - remote-access

jobs:
- template: chefspec-cookstyle.yml@templates
- template: test-kitchen.yml@templates
  parameters:
    jobName: "haswell"
    kitchenFile: kitchen.yml
    venturaPlus: true
    platforms:
      - ventura-x86
    # - ventura-arm
    suites: ${{ parameters.kitchenSuites }}
- template: test-kitchen.yml@templates
  parameters:
    jobName: "vintage"
    kitchenFile: kitchen.yml
    platforms:
      - big-sur-x86
      - monterey-x86
    suites: ${{ parameters.kitchenSuites }}
